id: IDC45BE2D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:02:54+00:00'
last_modified: '2022-06-07T20:30:37.503590+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74523
  title: ཐུའུ་བཀྭན་བླ་བྲང་དུ་ཞུགས་པའི་དཔེ་རྙིང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C3F4:
      image_group_id: I4CZ74525
      title: ''
      total_pages: 710
      order: 1
      base_file: C3F4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
