id: P004136
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74523
  title: ཐུའུ་བཀྭན་བླ་བྲང་དུ་ཞུགས་པའི་དཔེ་རྙིང་།
  author: ''
  volumes:
    39969f363c954e8687823a81b42eb534:
      image_group_id: I4CZ74525
      title: ''
      volume_number: 1
      total_pages: 710
