id: P004136
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:55:30.870685
source_metadata:
  id: bdr:W4CZ74523
  title: ཐུའུ་བཀྭན་བླ་བྲང་དུ་ཞུགས་པའི་དཔེ་རྙིང་།
  author: ''
  volumes:
    39969f363c954e8687823a81b42eb534:
      image_group_id: I4CZ74525
      title: ''
      volume_number: 1
      total_pages: 710
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
